georchestra:
  webapps:
    header:
        docker_image: georchestra/header:latest
        extra_environment:
        - name: JAVA_OPTS
          value: -Dgeorchestra.datadir=/etc/georchestra
  datadir:
    volume:
    - name: georchestra-datadir
      emptyDir: {}
    git:
      url: https://github.com/georchestra/datadir.git
      ref: docker-master
      #secret: my-private-ssh-key