georchestra:
  webapps:
    header:
      docker_image: georchestra/header:latest
      extra_environment: []
    cas:
      docker_image: georchestra/cas:latest
    geonetwork:
      jetty_monitoring: true
      ogc_api_records: true
    geoserver:
      jetty_monitoring: true
      extra_environment: []
    proxy:
      jetty_monitoring: true
  datadir:
    volume:
    - name: georchestra-datadir
      emptyDir: {}
    git:
      url: https://github.com/georchestra/datadir.git
      ref: docker-master
      #secret: my-private-ssh-key
  storage:
    gn4_es_data_size: 2Gi
    geonetwork_datadir_size: 2Gi
    geoserver_datadir_size: 256Mi
    geoserver_geodata_size: 2Gi
    mapstore_datadir_size: 256Mi
    openldap_data_size: 256Mi
    openldap_config_size: 1Mi
  smtp_smarthost:
    enabled: false
    # mailname: georchestra-127-0-1-1.traefik.me
    # postmaster: postmaster@georchestra-127-0-1-1.traefik.me
    # relay_host: my-external-smtp
    # relay_port: 25
    # relay_username:  aaaa
    # relay_password:  aaaa
