georchestra:
  webapps:
    analytics:
      docker_image: georchestra/analytics:latest
    cas:
      docker_image: georchestra/cas:latest
    console:
      docker_image: georchestra/console:latest
    datafeeder:
      docker_image: georchestra/datafeeder:latest
    datafeeder_frontend:
      docker_image: georchestra/datafeeder-frontend:latest
    extractorapp:
      docker_image: georchestra/extractorapp:latest
    geonetwork:
      docker_image: georchestra/geonetwork:latest
      jetty_monitoring: true
      ogc_api_records: true
      ogc_api_records_image: georchestra/gn-cloud-ogc-api-records-service:2021-12-16
      es_image: elasticsearch:7.9.0
      kibana_image: kibana:7.9.0
    geoserver:
      docker_image: georchestra/geoserver:latest
      jetty_monitoring: true
      extra_environment: []
    header:
      docker_image: georchestra/header:latest
      extra_environment: []
    mapfishapp:
      docker_image: georchestra/mapfishapp:latest
    mapstore:
      docker_image: georchestra/mapstore:latest
    openldap:
      docker_image: georchestra/ldap:latest
    proxy:
      docker_image: georchestra/security-proxy:latest
      jetty_monitoring: true
  datadir:
    volume:
    - name: georchestra-datadir
      emptyDir: {}
    git:
      url: https://github.com/georchestra/datadir.git
      ref: docker-master
      #secret: my-private-ssh-key
  storage:
    gn4_es_data_size: 2Gi
    geonetwork_datadir_size: 2Gi
    geoserver_datadir_size: 256Mi
    geoserver_geodata_size: 2Gi
    mapstore_datadir_size: 256Mi
    openldap_data_size: 256Mi
    openldap_config_size: 1Mi
    storage_class_name: default
  smtp_smarthost:
    enabled: false
    # mailname: georchestra-127-0-1-1.traefik.me
    # postmaster: postmaster@georchestra-127-0-1-1.traefik.me
    # relay_host: my-external-smtp
    # relay_port: 25
    # relay_username:  aaaa
    # relay_password:  aaaa
