---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-datafeeder
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-datafeeder
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-datafeeder
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-datafeeder
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-datafeeder
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      initContainers:
      {{- include "georchestra.bootstrap_georchestra_datadir" . | nindent 6 }}
      containers:
      - name: georchestra-datafeeder
        image: {{ .Values.georchestra.webapps.datafeeder.docker_image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-proxy
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
          - mountPath: /tmp/datafeeder
            name: datafeeder-uploads
        livenessProbe:
          tcpSocket:
            port: http-proxy
          periodSeconds: 10
          initialDelaySeconds: 20
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      - name: datafeeder-uploads
        emptyDir: {}
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
      {{- if .Values.georchestra.webapps.datafeeder.registry_secret }}
      imagePullSecrets:
      - name: {{ .Values.georchestra.webapps.datafeeder.registry_secret }}
      {{- end }}
