apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra.fullname" . }}-import-svc
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ include "georchestra.fullname" . }}-import
