apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-import
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-import
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: georchestra-import
        image: georchestra/datafeeder-frontend:21.0-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
