apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-import
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-import
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: georchestra-import
        image: {{ .Values.georchestra.webapps.datafeeder_frontend.docker_image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          tcpSocket:
            port: 80
          failureThreshold: 5
          periodSeconds: 5
      {{- if .Values.georchestra.webapps.datafeeder_frontend.registry_secret }}
      imagePullSecrets:
      - name: {{ .Values.georchestra.webapps.datafeeder_frontend.registry_secret }}
      {{- end }}
