---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-cas
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-cas
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-cas
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-cas
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-cas
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      initContainers:
      - name: bootstrap-georchestra-datadir
        image: bitnami/git
        command:
        - /bin/sh
        - -c
        - mkdir -p /root/.ssh ;
          cp /ssh-secret/ssh-privatekey /root/.ssh/id_rsa ;
          chmod 0600 /root/.ssh/id_rsa ;
         git clone {{ .Values.georchestra.datadir.git.url }} -b {{ .Values.georchestra.datadir.git.ref }} /etc/georchestra
        env:
        {{- if .Values.georchestra.datadir.git.ssh_secret }}
        - name: GIT_SSH_COMMAND
          value: ssh -o "IdentitiesOnly=yes" -o "StrictHostKeyChecking no"
        {{- end }}
        volumeMounts:
        - mountPath: /etc/georchestra
          name: georchestra-datadir
        {{- if .Values.georchestra.datadir.git.ssh_secret }}
        - mountPath: /ssh-secret
          name: ssh-secret
        {{- end }}
      - name: prepare-cas-webapp
        image: {{ .Values.georchestra.webapps.cas.docker_image }}
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/georchestra
          name: georchestra-datadir
        - mountPath: /cas-webapp
          name: cas-webapp
        command:
        - /bin/sh
        - -c
        - cp -r /var/lib/jetty/webapps/cas/* /cas-webapp ;
          if [ -d /etc/georchestra/cas/themes ] ; then
            cp -rvf /etc/georchestra/cas/themes /cas-webapp/WEB-INF/classes/static/ ;
          fi ;
          if [ -d /etc/georchestra/cas/templates ] ; then
            cp -rvf /etc/georchestra/cas/templates /cas-webapp/WEB-INF/classes/ ;
          fi
      containers:
      - name: georchestra-cas
        image: {{ .Values.georchestra.webapps.cas.docker_image }}
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
          - mountPath: /var/lib/jetty/webapps/cas
            name: cas-webapp
        ports:
        - containerPort: 8080
          name: http-proxy
        livenessProbe:
          httpGet:
            path: /cas/login
            port: 8080
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 5
          periodSeconds: 60
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      - name: cas-webapp
        emptyDir: {}
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
      {{- if .Values.georchestra.webapps.cas.registry_secret }}
      imagePullSecrets:
      - name: {{ .Values.georchestra.webapps.cas.registry_secret }}
      {{- end }}
