---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-extractorapp
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-extractorapp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      initContainers:
      - name: bootstrap-georchestra-datadir
        image: bitnami/git
        command:
        - /bin/sh
        - -c
        - mkdir -p /root/.ssh ;
          cp /ssh-secret/ssh-privatekey /root/.ssh/id_rsa ;
          chmod 0600 /root/.ssh/id_rsa ;
         git clone {{ .Values.georchestra.datadir.git.url }} -b {{ .Values.georchestra.datadir.git.ref }} /etc/georchestra
        env:
        {{- if .Values.georchestra.datadir.git.ssh_secret }}
        - name: GIT_SSH_COMMAND
          value: ssh -o "IdentitiesOnly=yes" -o "StrictHostKeyChecking no"
        {{- end }}
        volumeMounts:
        - mountPath: /etc/georchestra
          name: georchestra-datadir
        {{- if .Values.georchestra.datadir.git.ssh_secret }}
        - mountPath: /ssh-secret
          name: ssh-secret
        {{- end }}
      containers:
      - name: georchestra-extractorapp
        image: {{ .Values.georchestra.webapps.extractorapp.docker_image }}
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
        ports:
        - containerPort: 8080
          name: http-proxy
        livenessProbe:
          httpGet:
            path: /extractorapp/extractor/tasks
            port: 8080
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 5
          periodSeconds: 20
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
