apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geonetwork-datadir
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: {{ .Values.georchestra.storage.geonetwork_datadir_size }}
