---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-geoserver
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-geoserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-geoserver
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-geoserver
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-geoserver
      {{- $webapp := .Values.georchestra.webapps.geoserver }}
      {{- if $webapp.jetty_monitoring }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9103"
        prometheus.io/scrape: "true"
      {{- end }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      securityContext:
        fsGroup: 999
      initContainers:
      - name: bootstrap-georchestra-datadir
        image: bitnami/git
        command:
        - /bin/sh
        - -c
        - mkdir -p /root/.ssh ;
          cp /ssh-secret/ssh-privatekey /root/.ssh/id_rsa ;
          chmod 0600 /root/.ssh/id_rsa ;
         git clone {{ .Values.georchestra.datadir.git.url }} -b {{ .Values.georchestra.datadir.git.ref }} /etc/georchestra
        env:
        {{- if .Values.georchestra.datadir.git.ssh_secret }}
        - name: GIT_SSH_COMMAND
          value: ssh -o "IdentitiesOnly=yes" -o "StrictHostKeyChecking no"
        {{- end }}
        volumeMounts:
        - mountPath: /etc/georchestra
          name: georchestra-datadir
        {{- if .Values.georchestra.datadir.git.ssh_secret }}
        - mountPath: /ssh-secret
          name: ssh-secret
        {{- end }}
      - name: prepare-geoserver-webapp
        image: {{ .Values.georchestra.webapps.geoserver.docker_image }}
        command:
        - /bin/sh
        - -c
        - cp -r /var/lib/jetty/webapps/geoserver/* /mnt/geoserver_webapp ;
          if [ -f /mnt/georchestra_datadir/geoserver/jetty-env.xml ] ; then
            cp /mnt/georchestra_datadir/geoserver/jetty-env.xml /mnt/geoserver_webapp/WEB-INF/jetty-env.xml ;
          fi ;
        volumeMounts:
          - name: georchestra-datadir
            mountPath: /mnt/georchestra_datadir
          - name: geoserver-webapp
            mountPath: /mnt/geoserver_webapp
      containers:
      - name: georchestra-geoserver
        image: {{ .Values.georchestra.webapps.geoserver.docker_image }}
        imagePullPolicy: Always
        {{- if $webapp.extra_environment }}
        env:
          {{- $webapp.extra_environment | toYaml | nindent 8 }}
        {{- end }}
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
          - mountPath: /mnt/geoserver_geodata
            name: geoserver-geodata
          - mountPath: /mnt/geoserver_datadir
            name: geoserver-datadir
          - mountPath: /var/lib/jetty/webapps/geoserver
            name: geoserver-webapp
        ports:
        - containerPort: 8080
          name: http-proxy
        {{- if $webapp.custom_liveness_probe }}
        {{ $webapp.custom_liveness_probe | toYaml | nindent 8 }}
        {{- else }}
        livenessProbe:
          httpGet:
            path: /geoserver/gwc/service/wmts?SERVICE=WMTS&REQUEST=GetCapabilities
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
        {{- end }}
        startupProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 5
          periodSeconds: 40
      {{- if $webapp.jetty_monitoring }}
      - name: jmx-collectd
        image: camptocamp/jmx-collectd:bullseye
        volumeMounts:
        - mountPath: /collectd-template
          name: georchestra-monitoring-cm
        ports:
        - containerPort: 9103
          name: prometheus
        command:
        - /bin/sh
        - -c
        - mkdir /etc/collectd/collectd.conf.d/ ;
          cat /collectd-template/collectd-jmx-jetty.conf | sed "s/localhost/$(hostname)/g" > /etc/collectd/collectd.conf.d/jmx.conf ;
          collectd -f
      {{- end }}
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      - name: geoserver-webapp
        emptyDir: {}
      - name: geoserver-geodata
        persistentVolumeClaim:
          claimName: {{ include "georchestra.fullname" . }}-geoserver-geodata
      - name: geoserver-datadir
        persistentVolumeClaim:
          claimName: {{ include "georchestra.fullname" . }}-geoserver-datadir
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
      {{- if $webapp.jetty_monitoring }}
      - name: georchestra-monitoring-cm
        configMap:
          name: {{ include "georchestra.fullname" . }}-monitoring-cm
      {{- end }}
      {{- if .Values.georchestra.webapps.geoserver.registry_secret }}
      imagePullSecrets:
      - name: {{ .Values.georchestra.webapps.geoserver.registry_secret }}
      {{- end }}
