apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserver-geodata
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: {{ .Values.georchestra.storage.geoserver_geodata_size }}
