apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserver-datadir
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: default
  resources:
    requests:
      storage: {{ .Values.georchestra.storage.geoserver_datadir_size }}
