apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "georchestra.fullname" . }}-geoserver-geodata
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.georchestra.storage.storage_class_name }}
  resources:
    requests:
      storage: {{ .Values.georchestra.storage.geoserver_geodata_size }}
