---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: georchestra-header
spec:
  replicas: 1
  selector:
    matchLabels:
      app: georchestra-header
  template:
    metadata:
      labels:
        app: georchestra-header
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      initContainers:
      - name: bootstrap-georchestra-datadir
        image: bitnami/git
        command:
        - /bin/sh
        - -c
        - mkdir -p /root/.ssh ;
          cp /ssh-secret/ssh-privatekey /root/.ssh/id_rsa ;
          chmod 0600 /root/.ssh/id_rsa ;
         git clone {{ .Values.georchestra.datadir.git.url }} -b {{ .Values.georchestra.datadir.git.ref }} /etc/georchestra
        env:
        {{- if .Values.georchestra.datadir.git.ssh_secret }}
        - name: GIT_SSH_COMMAND
          value: ssh -o "IdentitiesOnly=yes" -o "StrictHostKeyChecking no"
        {{- end }}
        volumeMounts:
        - mountPath: /etc/georchestra
          name: georchestra-datadir
        {{- if .Values.georchestra.datadir.git.ssh_secret }}
        - mountPath: /ssh-secret
          name: ssh-secret
        {{- end }}
      containers:
      - name: georchestra-header
        image: {{ .Values.georchestra.webapps.header.docker_image }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 1024Mi
        env:
          {{- .Values.georchestra.webapps.header.extra_environment | toYaml | nindent 10 }}
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
        ports:
        - containerPort: 8080
          name: http-proxy
      imagePullSecrets:
      - name: dockerhub-biotope-registry
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
