---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-mapstore
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-mapstore
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-mapstore
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-mapstore
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-mapstore
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      initContainers:
      - name: bootstrap-georchestra-datadir
        image: bitnami/git
        command:
        - /bin/bash
        - -c
        - rm -rf /mapstore_datadir/* ;
          mkdir -p /root/.ssh ;
          cp /ssh-secret/ssh-privatekey /root/.ssh/id_rsa ;
          chmod 0600 /root/.ssh/id_rsa ;
          git clone {{ .Values.georchestra.datadir.git.url }} -b {{ .Values.georchestra.datadir.git.ref }} /etc/georchestra ;
        env:
        {{- if .Values.georchestra.datadir.git.ssh_secret }}
        - name: GIT_SSH_COMMAND
          value: ssh -o "IdentitiesOnly=yes" -o "StrictHostKeyChecking no"
        {{- end }}
        volumeMounts:
        - mountPath: /etc/georchestra
          name: georchestra-datadir
        {{- if .Values.georchestra.datadir.git.ssh_secret }}
        - mountPath: /ssh-secret
          name: ssh-secret
        {{- end }}
      containers:
      - name: georchestra-mapstore
        image: {{ .Values.georchestra.webapps.mapstore.docker_image }}
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
          - mountPath: /mnt/mapstore2
            name: mapstore-datadir
        env:
        - name: JAVA_OPTS
          value: -Xms512m -Xmx1G -XX:MaxPermSize=128m -DPRINT_BASE_URL=pdf -Dgeorchestra.datadir=/etc/georchestra -Dgeorchestra.extensions=/mnt/mapstore2
        ports:
        - containerPort: 8080
          name: http-proxy
        livenessProbe:
          httpGet:
            path: /mapstore/configs/config.json
            port: 8080
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /mapstore/configs/config.json
            port: 8080
          failureThreshold: 5
          periodSeconds: 15
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      - name: mapstore-datadir
        persistentVolumeClaim:
          claimName: {{ include "georchestra.fullname" . }}-mapstore-datadir
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
      {{- if .Values.georchestra.webapps.mapstore.registry_secret }}
      imagePullSecrets:
      - name: {{ .Values.georchestra.webapps.mapstore.registry_secret }}
      {{- end }}
