---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra.fullname" . }}-mapstore-svc
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ include "georchestra.fullname" . }}-mapstore
