apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mapstore-datadir
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: {{ .Values.georchestra.storage.mapstore_datadir_size }}
