apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "georchestra.fullname" . }}-mapstore-datadir
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: {{ .Values.georchestra.storage.mapstore_datadir_size }}
