---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra.fullname" . }}-ldap-svc
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
spec:
  ports:
  - port: 389
    protocol: TCP
    targetPort: 389
  selector:
    org.georchestra.service/name: {{ include "georchestra.fullname" . }}-ldap
