apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: {{ .Values.georchestra.storage.openldap_data_size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-config
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: {{ .Values.georchestra.storage.openldap_config_size }}
