---
# sp
apiVersion: apps/v1
kind: Deployment
metadata:
  name: georchestra-sp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: georchestra-sp
  template:
    metadata:
      labels:
        app: georchestra-sp
      {{- $webapp := .Values.georchestra.webapps.proxy }}
      {{- if $webapp.jetty_monitoring }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9103"
        prometheus.io/scrape: "true"
      {{- end }}
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      initContainers:
      - name: bootstrap-georchestra-datadir
        image: bitnami/git
        command:
        - /bin/sh
        - -c
        - mkdir -p /root/.ssh ;
          cp /ssh-secret/ssh-privatekey /root/.ssh/id_rsa ;
          chmod 0600 /root/.ssh/id_rsa ;
         git clone {{ .Values.georchestra.datadir.git.url }} -b {{ .Values.georchestra.datadir.git.ref }} /etc/georchestra
        env:
        {{- if .Values.georchestra.datadir.git.ssh_secret }}
        - name: GIT_SSH_COMMAND
          value: ssh -o "IdentitiesOnly=yes" -o "StrictHostKeyChecking no"
        {{- end }}
        volumeMounts:
        - mountPath: /etc/georchestra
          name: georchestra-datadir
        {{- if .Values.georchestra.datadir.git.ssh_secret }}
        - mountPath: /ssh-secret
          name: ssh-secret
        {{- end }}
      containers:
      - name: georchestra-sp
        image: georchestra/security-proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-proxy
      {{- if $webapp.jetty_monitoring }}
      - name: jmx-collectd
        image: camptocamp/jmx-collectd:bullseye
        volumeMounts:
        - mountPath: /collectd-template
          name: georchestra-monitoring-cm
        ports:
        - containerPort: 9103
          name: prometheus
        command:
        - /bin/sh
        - -c
        - mkdir /etc/collectd/collectd.conf.d/ ;
          cat /collectd-template/collectd-jmx-jetty.conf | sed "s/localhost/$(hostname)/g" > /etc/collectd/collectd.conf.d/jmx.conf ;
          collectd -f
      {{- end }}
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
      {{- if $webapp.jetty_monitoring }}
      - name: georchestra-monitoring-cm
        configMap:
          name: georchestra-monitoring-cm
      {{- end }}
