apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gn4-es-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: {{ .Values.georchestra.storage.gn4_es_data_size }}
