apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "georchestra.fullname" . }}-gn4-es-data
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: {{ .Values.georchestra.storage.gn4_es_data_size }}
