---
apiVersion: v1
kind: Service
metadata:
  name: georchestra-gn4-elasticsearch-svc
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: georchestra-gn4-elasticsearch
