---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra.fullname" . }}-gn4-kibana-svc
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: {{ include "georchestra.fullname" . }}-gn4-kibana
