{{- if .Values.georchestra.webapps.geonetwork.ogc_api_records -}}
--- 
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra.fullname" . }}-gn4-ogc-api-records-svc
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    org.georchestra.service/name: {{ include "georchestra.fullname" . }}-gn4-ogc-api-records
{{- end -}}
